language: cpp
dist: xenial
sudo: required
group: edge
compiler: clang

python:
    - "3.7"

addons:
    apt:
        packages:
            - python-ruamel.yaml
            - python-jinja2

matrix:
  include:
  - os: linux
    python: 3.7
  - os: osx
    osx_image: xcode10.2
    python: 3.7

script:
  - |
    cmake . -DENABLE_OPENMP=off -DCMAKE_BUILD_TYPE=Debug
    make faunus -j
    ./faunus --version || travis_terminate 1;
    make unittests -j
    ./unittests || travis_terminate 1;
    make pyfaunus -j

