# Conda environment definition for development
#
#     conda env create -f environment.yml
#     source activate faunusdev
#
name: faunusdev
channels:
    - conda-forge/label/gcc7
    - defaults
dependencies:
    - clangdev
    - libcxx
    - cmake>=3.25
    - python=3
    - pandoc=2
    - pypandoc=1
    - beautifulsoup4=4
    - scipy=1
    - pygments=2
    - jinja2=2.10
    - numpy=1.16
    - notebook=5
    - nbconvert=5
    - jupyter_contrib_nbextensions
    - sdl2=2
    - jsonschema=3
    - ruamel.yaml

